"""Added default value for sample status

Revision ID: 32775e60ffe3
Revises: 670e6e7b6d5f
Create Date: 2024-09-25 11:40:31.652258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32775e60ffe3'
down_revision = '670e6e7b6d5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
